version: "3.8"
services:
  frontend:
    build:
      context: ./aimeth
      dockerfile: Dockerfile
    networks:
      - app-network
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - USER=${USER}
      - USERPASS=${USERPASS}
      - ADMIN=${ADMIN}
      - ADMINPASS=${ADMINPASS}
    networks:
      - app-network
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Custom Nginx configuration file
    ports:
      - 3300:80 # Expose only the proxy
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
